FROM nginx:1.29.0
COPY index.html /usr/share/nginx/html/index.html

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG BUILDPLATFORM
ARG BUILDOS
ARG BUILDARCH
ARG BUILDVARIANT

RUN echo "TARGETPLATFORM=${TARGETPLATFORM}"
RUN echo "TARGETOS=${TARGETOS}"
RUN echo "TARGETARCH=${TARGETARCH}"
RUN echo "TARGETVARIANT=${TARGETVARIANT}"
RUN echo "BUILDPLATFORM=${BUILDPLATFORM}"
RUN echo "BUILDOS=${BUILDOS}"
RUN echo "BUILDARCH=${BUILDARCH}"
RUN echo "BUILDVARIANT=${BUILDVARIANT}"