[package]
name = "myapp"
version = "0.1.0"
edition = "2024"

[dependencies]
# HTTP server
rocket = { version = "0.5.1" }

# Async runtime
tokio = { version = "1", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0"}